version: 0.1
phases:
  install:
    commands:
      - pip install --upgrade --user awscli
  build:
    commands:
      - npm install time
      - cd src; npm install; cd ..
      - find src/node_modules -type f -print -exec touch {} \;  # ZIP does not support timestamps before 1980
      - aws cloudformation package
         --template-file ./templates/template.yaml
         --s3-bucket $S3_BUCKET_NAME
         --output-template-file samTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
