AWSTemplateFormatVersion: "2010-09-09"
Outputs:
  NatGatewayId:
    Value: !Ref NAT
Parameters:
  PublicSubnetId:
    Type: "AWS::EC2::Subnet::Id"
  RouteTableId:
    Type: String
Resources:
  NAT:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !Ref PublicSubnetId
  EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
  NatRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTableId
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NAT
